# Generated by Django 5.1 on 2024-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
