# Generated by Django 5.1 on 2024-08-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='designation',
            new_name='designation_id',
        ),
    ]
