# Generated by Django 5.1 on 2024-08-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_rename_department_user_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='designation_id',
            new_name='designation',
        ),
    ]
