# Generated by Django 5.1 on 2024-08-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_complexity_prority_sdlc_stage_type'),
        ('project_management', '0001_initial'),
        ('user_management', '0002_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prority',
            new_name='Priority',
        ),
    ]
