# Generated by Django 5.1 on 2024-08-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation', '0003_rename_prority_priority'),
        ('user_management', '0004_rename_department_id_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to='user_management.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_created_by', to='user_management.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_updated_by', to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_created_by', to='user_management.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_updated_by', to='user_management.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.solution')),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usecase_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecase_created_by', to='user_management.user')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.feature')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.solution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usecase_updated_by', to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_hours', models.IntegerField(default=0)),
                ('actual_hours', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_history_assignee', to='user_management.user')),
                ('complexity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.complexity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history_created_by', to='user_management.user')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.feature')),
                ('opened_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_history_opened_by', to='user_management.user')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.priority')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('sdlc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.sdlc')),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.solution')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.stage')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_history_updated_by', to='user_management.user')),
                ('usecase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('est_hours', models.IntegerField(default=0)),
                ('actual_hours', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignee', to='user_management.user')),
                ('complexity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.complexity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_created_by', to='user_management.user')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.feature')),
                ('opened_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_opened_by', to='user_management.user')),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.priority')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
                ('sdlc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.sdlc')),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.solution')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.stage')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.status')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_updated_by', to='user_management.user')),
                ('usecase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.usecase')),
            ],
        ),
    ]
